# ----------------------- #
#    Deploy Configs       #
# ----------------------- #

## -- Rsync Deploy config -- ##
# Be sure your public key is listed in your server's ~/.ssh/authorized_keys file
ssh_user: "user@domain.com"
ssh_port: "22"
document_root: "~/website.com/"
rsync_delete: false
rsync_args: ""  # Any extra arguments to pass to rsync
deploy_default: "push"

# This will be configured for you when you run config_deploy
deploy_branch: "gh-pages"
